<?xml version="1.0"?>

<!--
// Copyright 2022 Stereolabs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:macro name="zed_camera"
    params="parent_link xyz rpy
    model:=zed
    namespace:=None
    tf_prefix:=None
    name:=camera
    simulation_engine:=ignition-gazebo">

    <xacro:if value="${namespace == 'None'}">
      <xacro:property name="ns" value="" />
    </xacro:if>
    <xacro:unless value="${namespace == 'None'}">
      <xacro:property name="ns" value="${namespace}/" />
    </xacro:unless>

    <xacro:if value="${tf_prefix == 'None'}">
      <xacro:property name="prefix" value="" />
    </xacro:if>
    <xacro:unless value="${tf_prefix == 'None'}">
      <xacro:property name="prefix" value="${tf_prefix}_" />
    </xacro:unless>

    <xacro:if value="${model == 'zed'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.05" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zedm'}">
      <xacro:property name="baseline" value="0.06" />
      <xacro:property name="height" value="0.0265" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="0.0" />
    </xacro:if>
    <xacro:if value="${model == 'zed2'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.05" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zed2i'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="-0.01" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zedx'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.032" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="-0.016" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zedxm'}">
      <xacro:property name="baseline" value="0.05" />
      <xacro:property name="height" value="0.032" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="-0.016" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>

    <!-- Camera mounting point (the threaded screw hole in the bottom) -->
    <link name="${prefix}${name}_camera_link" />
    <joint name="${prefix}${name}_base_joint" type="fixed">
      <parent link="${parent_link}" />
      <child link="${prefix}${name}_camera_link" />
      <origin xyz="${xyz}" rpy="${rpy}" />
    </joint>

    <!-- Camera Center -->
    <link name="${prefix}${name}_camera_center">
      <visual>
        <origin xyz="${screw_offset_x} 0 ${screw_offset_z}" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://ros_components_description/meshes/${model}.stl" />
        </geometry>
        <material name="mat">
          <color rgba="0.25 0.25 0.25 0.99" />
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ros_components_description/meshes/${model}.stl" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}${name}_camera_center_joint" type="fixed">
      <parent link="${prefix}${name}_camera_link" />
      <child link="${prefix}${name}_camera_center" />
      <origin xyz="0 0 ${height/2}" rpy="0 ${bottom_slope} 0" />
    </joint>

    <!-- Artificially Created Camera Center -->
    <link name="${prefix}${name}_center_optical_frame" />
    <joint name="${prefix}${name}_center_joint" type="fixed">
      <parent link="${prefix}${name}_camera_center" />
      <child link="${prefix}${name}_center_optical_frame" />
      <origin xyz="0.01 0 0" rpy="0 0 0" />
    </joint>


    <xacro:if value="${simulation_engine == 'ignition-gazebo'}">
      <!-- It is also possible to use single rgbd_camera sensor, but using separate rgb and depth
      camera
        should be more accurate different frames and fovs can be set -->
      <gazebo reference="${prefix}${name}_center_optical_frame">
        <sensor type="rgbd_camera" name="${ns}${prefix}${name}_stereolabs_zed_rgbd">
          <always_on>true</always_on>
          <!-- <update_rate>30.0</update_rate> -->
          <update_rate>15.0</update_rate>

          <!-- <topic>${ns}${prefix}${name}/zed_node/rgb/image_rect_color</topic> -->
          <topic>rgbd_camera</topic>
          <visualize>false</visualize>
          <frame_id>${prefix}${name}_center_optical_frame</frame_id>
          <!-- <gz_frame_id>${prefix}${name}_center_optical_frame</gz_frame_id> -->
          <ignition_frame_id>${prefix}${name}_center_optical_frame</ignition_frame_id>
          
          <camera>
            <horizontal_fov>${110.0/180.0*pi}</horizontal_fov>
            <image>
              <!-- <width>1920</width>
              <height>1080</height> -->
              <width>1280</width>
              <height>720</height>
              <!-- <format>R8G8B8</format> -->
            </image>
            <clip>
              <near>0.3</near>
              <far>20.0</far>
            </clip>
          </camera>
          <ros>
            <namespace>${ns}</namespace>
          </ros>
        </sensor>
      </gazebo>
    </xacro:if>

  </xacro:macro>
</robot>
